## Large Arrays

In [90]:
import urllib

local_fname = 'weather-buoy-data.txt.gz'
urllib.request.urlretrieve('https://www.ndbc.noaa.gov/data/historical/stdmet/42040h2021.txt.gz', local_fname)

('weather-buoy-data.txt.gz', <http.client.HTTPMessage at 0x117339bd0>)

In [91]:
import gzip

f = iter(gzip.open('weather-buoy-data.txt.gz'))
next(f)
next(f)
vals = []
for line in f:
    vals.append(float(line.split()[5]))

In [92]:
import numpy as np

orig = (vals[0] + (np.arange(len(vals)) % 10) / 11).reshape((16,2333))

array([[88.     , 88.09091, 88.18182, 88.27273, ..., 88.81818, 88.     ,
        88.09091, 88.18182],
       [88.27273, 88.36364, 88.45455, 88.54545, ..., 88.18182, 88.27273,
        88.36364, 88.45455],
       [88.54545, 88.63636, 88.72727, 88.81818, ..., 88.45455, 88.54545,
        88.63636, 88.72727],
       [88.81818, 88.     , 88.09091, 88.18182, ..., 88.72727, 88.81818,
        88.     , 88.09091],
       ...,
       [88.54545, 88.63636, 88.72727, 88.81818, ..., 88.45455, 88.54545,
        88.63636, 88.72727],
       [88.81818, 88.     , 88.09091, 88.18182, ..., 88.72727, 88.81818,
        88.     , 88.09091],
       [88.18182, 88.27273, 88.36364, 88.45455, ..., 88.09091, 88.18182,
        88.27273, 88.36364],
       [88.45455, 88.54545, 88.63636, 88.72727, ..., 88.36364, 88.45455,
        88.54545, 88.63636]])

In [93]:
import numpy as np
a = np.round(orig, 2)

array([[88.  , 88.09, 88.18, 88.27, ..., 88.82, 88.  , 88.09, 88.18],
       [88.27, 88.36, 88.45, 88.55, ..., 88.18, 88.27, 88.36, 88.45],
       [88.55, 88.64, 88.73, 88.82, ..., 88.45, 88.55, 88.64, 88.73],
       [88.82, 88.  , 88.09, 88.18, ..., 88.73, 88.82, 88.  , 88.09],
       ...,
       [88.55, 88.64, 88.73, 88.82, ..., 88.45, 88.55, 88.64, 88.73],
       [88.82, 88.  , 88.09, 88.18, ..., 88.73, 88.82, 88.  , 88.09],
       [88.18, 88.27, 88.36, 88.45, ..., 88.09, 88.18, 88.27, 88.36],
       [88.45, 88.55, 88.64, 88.73, ..., 88.36, 88.45, 88.55, 88.64]])

In [94]:
b = np.floor(orig*100)/100

array([[88.  , 88.09, 88.18, 88.27, ..., 88.81, 88.  , 88.09, 88.18],
       [88.27, 88.36, 88.45, 88.54, ..., 88.18, 88.27, 88.36, 88.45],
       [88.54, 88.63, 88.72, 88.81, ..., 88.45, 88.54, 88.63, 88.72],
       [88.81, 88.  , 88.09, 88.18, ..., 88.72, 88.81, 88.  , 88.09],
       ...,
       [88.54, 88.63, 88.72, 88.81, ..., 88.45, 88.54, 88.63, 88.72],
       [88.81, 88.  , 88.09, 88.18, ..., 88.72, 88.81, 88.  , 88.09],
       [88.18, 88.27, 88.36, 88.45, ..., 88.09, 88.18, 88.27, 88.36],
       [88.45, 88.54, 88.63, 88.72, ..., 88.36, 88.45, 88.54, 88.63]])

In [95]:
c = np.delete(a, 5, 1)

array([[88.  , 88.09, 88.18, 88.27, ..., 88.82, 88.  , 88.09, 88.18],
       [88.27, 88.36, 88.45, 88.55, ..., 88.18, 88.27, 88.36, 88.45],
       [88.55, 88.64, 88.73, 88.82, ..., 88.45, 88.55, 88.64, 88.73],
       [88.82, 88.  , 88.09, 88.18, ..., 88.73, 88.82, 88.  , 88.09],
       ...,
       [88.55, 88.64, 88.73, 88.82, ..., 88.45, 88.55, 88.64, 88.73],
       [88.82, 88.  , 88.09, 88.18, ..., 88.73, 88.82, 88.  , 88.09],
       [88.18, 88.27, 88.36, 88.45, ..., 88.09, 88.18, 88.27, 88.36],
       [88.45, 88.55, 88.64, 88.73, ..., 88.36, 88.45, 88.55, 88.64]])

In [96]:
np.array_equal(a,c)

False

In [97]:
a.shape, b.shape, c.shape

((16, 2333), (16, 2333), (16, 2332))

## Real-Time Data

In [43]:
import urllib

local_fname = 'fl-weather-alerts.json'
urllib.request.urlretrieve('https://api.weather.gov/alerts/active?area=FL', local_fname)

('fl-weather-alerts.json', <http.client.HTTPMessage at 0x11733b3a0>)

In [44]:
import json
d = json.load(open(local_fname));

In [46]:
len(d['features'])

181

In [49]:
[feat['properties']['headline'] for feat in d['features']]

['Tropical Storm Warning issued September 27 at 5:04PM EDT by NWS Tallahassee FL',
 'Tropical Storm Warning issued September 27 at 5:04PM EDT by NWS Tallahassee FL',
 'Tropical Storm Warning issued September 27 at 5:04PM EDT by NWS Tallahassee FL',
 'Tropical Storm Warning issued September 27 at 5:04PM EDT by NWS Tallahassee FL',
 'Tropical Storm Warning issued September 27 at 5:04PM EDT by NWS Tallahassee FL',
 'Tropical Storm Warning issued September 27 at 5:04PM EDT by NWS Tallahassee FL',
 'Tornado Warning issued September 27 at 5:03PM EDT until September 27 at 5:30PM EDT by NWS Miami FL',
 'Coastal Flood Statement issued September 27 at 5:01PM EDT until September 29 at 8:00PM EDT by NWS Miami FL',
 'Coastal Flood Statement issued September 27 at 5:01PM EDT until September 29 at 8:00PM EDT by NWS Miami FL',
 'Tornado Watch issued September 27 at 4:59PM EDT until September 28 at 5:00AM EDT by NWS Miami FL',
 'Tornado Watch issued September 27 at 4:59PM EDT until September 28 at 5:00